var inCourse = [
  { "教練圖檔": "avatar-01.jpg",
    "教練姓名": "Eva",
    "上課地點": "中山店",
    "上課時間": "2020-12-22 09:00~10:29",
    "課程名稱": "年間方案",
  },
  { "教練圖檔": "avatar-16.jpg",
    "教練姓名": "Jack",
    "上課地點": "信義店",
    "上課時間": "2020-12-20 10:00~10:59",
    "課程名稱": "標準方案",
  },  
];


var messages = [
  { "message編號": '0001',
    "messageType": 'text',
    "message內容": '你好，我是 Eva。',
    "發送者":  'notMe',   
    "message時間": '2021/05/13 10:59',
    "message圖片":  '',
  },
  { "message編號": '0002',
    "messageType": 'emoji',         
    "message內容": '麻煩幫我預約下周二，下午兩點到三點上課',
    "發送者":  'Me',   
    "message時間": '2021/05/13 11:02',
    "message圖片":  './emojis/1F600.png',
  },   
  { "message編號": '0002-1',
    "messageType": 'text',         
    "message內容": '麻煩幫我預約下周二，下午兩點到三點上課',
    "發送者":  'Me',   
    "message時間": '2021/05/13 11:02',
    "message圖片":  '',
  }, 
  { "message編號": '0003',
    "messageType": 'text',
    "message內容": '已預約好。',
    "發送者":  'notMe',   
    "message時間": '2021/05/13 11:28',
    "message圖片":  '',
  },
  { "message編號": '0004',
    "messageType": 'text',         
    "message內容": '今天午餐',
    "發送者":  'Me',   
    "message時間": '2021/05/13 11:31',
    "message圖片":  '',
  }, 
  { "message編號": '0004-1',
    "messageType": 'picture',         
    "message內容": '圖片',
    "發送者":  'Me',   
    "message時間": '2021/05/13 11:31',
    "message圖片": './antigua-food-stewed-chicken.jpg',
  },   
  { "message編號": '0005',
    "messageType": 'text',
    "message內容": '今天記得來上課。',
    "發送者":  'notMe',   
    "message時間": '2021/05/20 11:28',
    "message圖片":  '',
  },
  { "message編號": '0006',
    "messageType": 'text',         
    "message內容": '下午兩點',
    "發送者":  'NotMe',   
    "message時間": '2021/05/20 11:28',
    "message圖片":  '',
  }, 
  { "message編號": '0007',
    "messageType": 'text',         
    "message內容": 'OK',
    "發送者":  'Me',   
    "message時間": '2021/05/20 11:33',
    "message圖片":  '',
  }, 
  { "message編號": 'dummy',
    "messageType": 'text',         
    "message內容": '',
    "發送者":  'dummy',   
    "message時間": '',
    "message圖片":  '',
  },   
          
]; 

var msgNumber=4;